spring.application.name=${APP_NAME:auth-service}
server.port=${APP_PORT:8081}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/postgres?createDatabaseIfNotExists=true}
spring.datasource.username=${DATASOURCE_USERNAME:postgres}
spring.datasource.password=${DATASOURCE_PASSWORD:password}

# OAuth2 client configuration
oauth2.client.web.clientSecret=${CLIENT_SECRET_WEB:client-web}
oauth2.client.android.clientSecret=${CLIENT_SECRET_ANDROID:client-android}
facebook.clientId=${FACEBOOK_CLIENT_ID:}
facebook.clientSecret=${FACEBOOK_SECRET:}
google.clientId=${GOOGLE_CLIENT_ID:}
google.clientSecret=${GOOGLE_SECRET:}

# OAuth2 token configuration
oauth2.token.reuse-refresh-token=false

# Spring flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# Queue Settings
queue.send-notification-to-address.name=send-notification

social.webRedirectUrl=
social.mobileRedirectUrl=